version: '3.8'

services:
  mediawiki:
    image: mediawiki:latest
    container_name: mediawiki
    networks:
      - internal_net
    env_file:
      - mediawiki.env
    volumes:
      - mediawiki_data:/var/www/html
    ports:
      - "8085:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mediawiki_db
    networks:
      - internal_net
    env_file:
      - mediawiki.env
    volumes:
      - db_data:/var/lib/mysql

networks:
  internal_net:
    driver: bridge

volumes:
  mediawiki_data:
  db_data:
