version: '3.8'

services:
  gogs:
    image: gogs/gogs:latest
    container_name: gogs
    networks:
      - internal_net
    env_file:
      - gogs.env
    volumes:
      - gogs_data:/data
    ports:
      - "3000:3000"
      - "2222:22"  
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: gogs_db
    networks:
      - internal_net
    env_file:
      - gogs.env
    volumes:
      - db_data:/var/lib/mysql

networks:
  internal_net:
    driver: bridge

volumes:
  gogs_data:
  db_data:

