version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    networks:
      - internal_net
    env_file:
      - nextcloud.env
    volumes:
      - nextcloud_data:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: nextcloud_db
    networks:
      - internal_net
    env_file:
      - nextcloud.env
    volumes:
      - db_data:/var/lib/mysql

networks:
  internal_net:
    driver: bridge

volumes:
  nextcloud_data:
  db_data:
